spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_sys?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  port: 8080
debug: true
